# Generated by Django 2.1.5 on 2019-02-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='books',
        ),
    ]
