# Generated by Django 2.1.5 on 2019-02-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0002_remove_student_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBookRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_book.Book')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_book.Student')),
            ],
        ),
    ]
