# Generated by Django 2.1.5 on 2019-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0003_studentbookrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_no_of_pages_read',
            field=models.BigIntegerField(default=0),
        ),
    ]
