# Generated by Django 2.1.5 on 2019-02-18 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0005_auto_20190218_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
