# Generated by Django 2.1.5 on 2019-02-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0008_auto_20190218_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
